//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class C__MigrationHistory
{
    public string MigrationId { get; set; }
    public string ContextKey { get; set; }
    public byte[] Model { get; set; }
    public string ProductVersion { get; set; }
}

public partial class Compte
{
    public string login { get; set; }
    public string password { get; set; }
    public Nullable<int> idEleve { get; set; }
}

public partial class Eleve
{
    public int ID_Eleve { get; set; }
    public string CNE { get; set; }
    public string Prenom { get; set; }
    public string Nom { get; set; }
    public byte[] Photo { get; set; }
    public string Tel { get; set; }
    public string Email { get; set; }
}

public partial class Employee
{
    public int EmpId { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Gnedere { get; set; }
}
