//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationadmin2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Eleve", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Eleve : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_EleveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNE {
            get {
                return this.CNEField;
            }
            set {
                if ((object.ReferenceEquals(this.CNEField, value) != true)) {
                    this.CNEField = value;
                    this.RaisePropertyChanged("CNE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Eleve {
            get {
                return this.ID_EleveField;
            }
            set {
                if ((this.ID_EleveField.Equals(value) != true)) {
                    this.ID_EleveField = value;
                    this.RaisePropertyChanged("ID_Eleve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEleves", ReplyAction="http://tempuri.org/IService/GetElevesResponse")]
        WebApplicationadmin2.ServiceReference1.Eleve[] GetEleves();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEleves", ReplyAction="http://tempuri.org/IService/GetElevesResponse")]
        System.Threading.Tasks.Task<WebApplicationadmin2.ServiceReference1.Eleve[]> GetElevesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddStudent", ReplyAction="http://tempuri.org/IService/AddStudentResponse")]
        int AddStudent(int id, string cne, string prenom, string nom, string email, byte[] photo, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddStudent", ReplyAction="http://tempuri.org/IService/AddStudentResponse")]
        System.Threading.Tasks.Task<int> AddStudentAsync(int id, string cne, string prenom, string nom, string email, byte[] photo, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteById", ReplyAction="http://tempuri.org/IService/DeleteByIdResponse")]
        int DeleteById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteById", ReplyAction="http://tempuri.org/IService/DeleteByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateStudent", ReplyAction="http://tempuri.org/IService/UpdateStudentResponse")]
        int UpdateStudent(int id, string cne, string prenom, string nom, string email, byte[] photo, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateStudent", ReplyAction="http://tempuri.org/IService/UpdateStudentResponse")]
        System.Threading.Tasks.Task<int> UpdateStudentAsync(int id, string cne, string prenom, string nom, string email, byte[] photo, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudentById", ReplyAction="http://tempuri.org/IService/GetStudentByIdResponse")]
        WebApplicationadmin2.ServiceReference1.Eleve GetStudentById(int e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudentById", ReplyAction="http://tempuri.org/IService/GetStudentByIdResponse")]
        System.Threading.Tasks.Task<WebApplicationadmin2.ServiceReference1.Eleve> GetStudentByIdAsync(int e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudentByCNE", ReplyAction="http://tempuri.org/IService/GetStudentByCNEResponse")]
        WebApplicationadmin2.ServiceReference1.Eleve GetStudentByCNE(string cne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudentByCNE", ReplyAction="http://tempuri.org/IService/GetStudentByCNEResponse")]
        System.Threading.Tasks.Task<WebApplicationadmin2.ServiceReference1.Eleve> GetStudentByCNEAsync(string cne);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebApplicationadmin2.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebApplicationadmin2.ServiceReference1.IService>, WebApplicationadmin2.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplicationadmin2.ServiceReference1.Eleve[] GetEleves() {
            return base.Channel.GetEleves();
        }
        
        public System.Threading.Tasks.Task<WebApplicationadmin2.ServiceReference1.Eleve[]> GetElevesAsync() {
            return base.Channel.GetElevesAsync();
        }
        
        public int AddStudent(int id, string cne, string prenom, string nom, string email, byte[] photo, string tel) {
            return base.Channel.AddStudent(id, cne, prenom, nom, email, photo, tel);
        }
        
        public System.Threading.Tasks.Task<int> AddStudentAsync(int id, string cne, string prenom, string nom, string email, byte[] photo, string tel) {
            return base.Channel.AddStudentAsync(id, cne, prenom, nom, email, photo, tel);
        }
        
        public int DeleteById(int Id) {
            return base.Channel.DeleteById(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteByIdAsync(int Id) {
            return base.Channel.DeleteByIdAsync(Id);
        }
        
        public int UpdateStudent(int id, string cne, string prenom, string nom, string email, byte[] photo, string tel) {
            return base.Channel.UpdateStudent(id, cne, prenom, nom, email, photo, tel);
        }
        
        public System.Threading.Tasks.Task<int> UpdateStudentAsync(int id, string cne, string prenom, string nom, string email, byte[] photo, string tel) {
            return base.Channel.UpdateStudentAsync(id, cne, prenom, nom, email, photo, tel);
        }
        
        public WebApplicationadmin2.ServiceReference1.Eleve GetStudentById(int e) {
            return base.Channel.GetStudentById(e);
        }
        
        public System.Threading.Tasks.Task<WebApplicationadmin2.ServiceReference1.Eleve> GetStudentByIdAsync(int e) {
            return base.Channel.GetStudentByIdAsync(e);
        }
        
        public WebApplicationadmin2.ServiceReference1.Eleve GetStudentByCNE(string cne) {
            return base.Channel.GetStudentByCNE(cne);
        }
        
        public System.Threading.Tasks.Task<WebApplicationadmin2.ServiceReference1.Eleve> GetStudentByCNEAsync(string cne) {
            return base.Channel.GetStudentByCNEAsync(cne);
        }
    }
}
